"""
Django settings for chatdku_django project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import logging.config
from pathlib import Path
import logging
import os,base64
from django.utils.log import DEFAULT_LOGGING
field_key=base64.urlsafe_b64encode(os.urandom(32)).decode()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

FIELD_ENCRYPTION_KEY = os.environ.get('FIELD_ENCRYPTION_KEY', field_key)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY","hsafgb289yubdkbvq28yor2yq734ti14")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

#logging
LOGGING_CONFIG=None

LOGLEVEL=os.environ.get('LOGLEVEL','info').upper()
current_path=os.path.abspath(os.path.dirname(__file__))
logging.config.dictConfig({
    'version':1,
    'disable_existing_loggers':False,
    'formatters':{
        'default':{
            'format':'%(asctime)s %(name)-12s %(levelname)-8s %(message)s',
        },
        'django.server':DEFAULT_LOGGING['formatters']['django.server'],

    },
    'handlers':{
        'console':{
            'class':'logging.StreamHandler',
            'formatter':'default',
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(current_path,'log','chatdku.log'),  
            'maxBytes': 5 * 1024 * 1024,  # 5 MB
            'backupCount': 5,
            'formatter': 'default',
        },
        'django.server':DEFAULT_LOGGING['handlers']['django.server'],
    },
    'loggers':{
        '':{
            'level':'WARNING',
            'handlers':['console','file'],
        },
        'app':{
            'level':LOGLEVEL,
            'handlers':['console','file'],
            'propagate':False,
        },
        'django.server':DEFAULT_LOGGING['loggers']['django.server']
    },
})

ALLOWED_HOSTS = [
                "chatdku.dukekunshan.edu.cn",
                "10.200.14.82",
                "127.0.0.1:8009",
                "localhost:8009",
                 ]
#Proxy 
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')   

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'core.apps.CoreConfig',
    'import_export',
    'corsheaders',
    'chat',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'core.middleware.NetIDMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'chatdku_django.urls'
#CORS
CORS_ALLOWED_ORIGINS = [
    "https://chatdku.dukekunshan.edu.cn",
    "http://10.200.14.82",
]
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'chatdku_django.wsgi.application'

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
    ],
}
AUTH_USER_MODEL="core.UserModel"

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
SESSION_ENGINE = 'django.contrib.sessions.backends.db'

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

CSRF_TRUSTED_ORIGINS = [
    "https://chatdku.dukekunshan.edu.cn",
]
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True
SESSION_COOKIE_AGE = 1800
# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/


TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True
USE_L10N = True
LANGUAGE_CODE = 'en-us'

LANGUAGES = [
    ('en', 'English'),
    ('zh-hans', 'Chinese'),
]

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = 'https://chatdku.dukekunshan.edu.cn/django_static/'
STATIC_ROOT = os.path.join("/var/www/chatdku/", 'django_staticfiles')


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

