"""date removed

Revision ID: 225612aaf33f
Revises: 72e7656c297a
Create Date: 2025-05-29 19:41:42.473991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '225612aaf33f'
down_revision = '72e7656c297a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
