"""request table

Revision ID: 72e7656c297a
Revises: ae3073ac5fd4
Create Date: 2025-05-29 19:11:48.323610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72e7656c297a'
down_revision = 'ae3073ac5fd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request',
    sa.Column('date_', sa.DateTime(), nullable=False),
    sa.Column('req_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('date_'),
    sa.UniqueConstraint('date_')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('request')
    # ### end Alembic commands ###
