# Generated by Django 5.2.3 on 2025-06-30 15:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_input', models.TextField()),
                ('gen_answer', models.TextField()),
                ('feedback_reason', models.TextField(verbose_name='Feedback reason')),
                ('question_id', models.IntegerField(verbose_name='Question ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
