# Generated by Django 5.2.3 on 2025-07-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='question_id',
            field=models.TextField(verbose_name='Question ID'),
        ),
    ]
