import os

import transformers
from llama_index.core import Settings
from llama_index.embeddings.text_embeddings_inference import TextEmbeddingsInference
from phoenix.otel import register
from sqlalchemy import create_engine, text
from transformers import AutoTokenizer

from chatdku.config import config


def mydeepcopy(self, memo):
    return self


def setup(add_system_prompt: bool = False, use_llm: bool = True) -> None:
    """Setup common resources from command line arguments."""
    # A Text Embeddings Inference server is used to serve the embedding model
    # The endpoint should be of the format [base_url]/[author]/[model_name]
    Settings.embed_model = TextEmbeddingsInference(
        model_name=config.embedding,
        base_url=config.tei_url + "/" + config.embedding,
    )
    print(f"Using embedding model {config.embedding}")

    # Suppress warning
    # "Special tokens have been added in the vocabulary,
    # make sure the associated word embeddings are fine-tuned or trained."
    transformers.logging.set_verbosity_error()

    # The same tokenizer as used by the LLM is used to count the number of tokens
    # accurately.
    Settings.tokenizer = AutoTokenizer.from_pretrained(config.tokenizer)
    print("Loaded tokenizer")


def use_phoenix():
    phoenix_port = os.environ.get("PHOENIX_PORT", 6007)
    collector_endpoint = f"http://127.0.0.1:{phoenix_port}/v1/traces"
    tracer_provider = register(
        project_name="ChatDKU_student_release",  # Default is 'default'
        auto_instrument=True,  # See 'Trace all calls made to a library' below
        endpoint=collector_endpoint,
        batch=True,
    )
    config.tracer = tracer_provider.get_tracer(__name__)


class DB:
    """Hosts all functions for querying the database.

    Use the execute() method if you want to execute a single SQL
    statement (which will be in a transaction by itself.

    If you want to execute multiple SQL statements in the same
    transaction, use the following pattern:

    >>> with app.db.engine.begin() as conn:
    >>>     # everything in this block executes as one transaction
    >>>     value = conn.execute(text('SELECT...'), bar='foo').first()[0]
    >>>     conn.execute(text('INSERT...'), par=value)
    >>>     conn.execute(text('UPDATE...'), par=value)
    >>>

    """

    def __init__(self):
        # print(config.psql_uri)
        self.engine = create_engine(
            config.psql_uri, execution_options={"isolation_level": "SERIALIZABLE"}
        )

    def execute(self, sqlstr, **kwargs):
        """Execute a single SQL statement sqlstr.
        If the statement is a query or a modification with a RETURNING clause,
        return the list of result tuples;
        if the statement is an UPDATE or DELETE statement without RETURNING,
        return the rows matched by the WHERE criterion of the UPDATE or DELETE statement;
        otherwise, return None.
        An exception will be raised for any error encountered.
        sqlstr will be wrapped automatically in a sqlalchemy.sql.expression.TextClause.
        You can use :param inside sqlstr and supply its value as a kwarg.
        See
        https://docs.sqlalchemy.org/en/14/core/connections.html#sqlalchemy.engine.execute
        https://docs.sqlalchemy.org/en/14/core/sqlelement.html#sqlalchemy.sql.expression.text
        https://docs.sqlalchemy.org/en/14/core/connections.html#sqlalchemy.engine.CursorResult
        for additional details.
        """
        with self.engine.begin() as conn:
            # Apply a statement timeout to avoid very long-running queries caused
            # by malformed or runaway SQL generated by LLMs. Timeout value can
            # be configured via `config.psql_statement_timeout_ms` (milliseconds).
            timeout = getattr(config, "psql_statement_timeout_ms", 10000)
            try:
                conn.execute(text(f"SET LOCAL statement_timeout = {int(timeout)}"))
            except Exception:
                # If the DB doesn't support statement_timeout, continue anyway.
                pass
            result = conn.execute(text(sqlstr), kwargs)
            # Row object is truncating long fields like descriptions
            # so we are turning rows into tuples
            if result.returns_rows:
                return [
                    tuple(row) for row in result.fetchall()
                ]  # full strings, named columns
            else:
                return result.rowcount
