# Generated by Django 5.2.5 on 2026-01-27 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_activelm"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ActiveLM",
        ),
        migrations.AddField(
            model_name="usermodel",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
