import re

import dspy


class Text2SQLSignature(dspy.Signature):
    """
    Generates pure SQL given the user question, tables, and columns without any backticks, to be run on a database of the classes offered at Duke Kunshan University (DKU).
    Uses fuzzy search using regex, ILIKE, and % symbols when querying for a course or a person's name, as they may be inconsistent.
    Text fields course_code may or may not a space in the middle, so must be accounted for by adding the regex % between the name and the number.
    Do not write overly broad regex such as %cs%, as this can catch unrelated entries.
    Do not include the words professor or instructor when querying.
    Do not include any title, suffix, or honorifics when querying.
    Feel free to extract extra information using your query if it's helpful for the user's goals - such as instructor_name, course_title, year, semester.
    """

    natural_language_query = dspy.InputField(desc="Agent's natural language question")
    current_user_message = dspy.InputField(desc="User's initial prompt")
    sql_context = dspy.InputField(desc="PostgreSQL table schema.")
    reasoning = dspy.InputField(
        desc="If the SQL query judger said your generated query was invalid, the reasoning will be provided here."
    )
    sql = dspy.OutputField(desc="Pure, valid PostgreSQL query ending with semicolon")


class JudgeSQLSignature(dspy.Signature):
    """
    Judge the SQL query generated by another LLM agent.
    You are to check the validity of the SQL query, and whether the query follows
    the natural_language_query.
    """

    sql = dspy.InputField()
    natural_language_query = dspy.InputField(
        desc="The information the planner agent wants to retrieve by using this tool."
    )
    current_user_message = dspy.InputField(desc="User's initial prompt")
    judge: bool = dspy.OutputField(
        desc="Whether the SQL query is valid. Answer in `True` or `False`."
    )


class GenerateSQL(dspy.Module):
    def __init__(self):
        super().__init__()
        self.sql_generator = dspy.Predict(Text2SQLSignature)
        self.judger = dspy.ChainOfThought(JudgeSQLSignature)

    def forward(self, query, current_user_message, db_schema: str, N=3):
        reasoning = ""
        sql_result = ""
        for _ in range(N):
            sql_result = self.sql_generator(
                natural_language_query=query,
                current_user_message=current_user_message,
                reasoning=reasoning,
                sql_context=db_schema,
            )
            sql_result = sanitize_sql(extract_sql_regex(sql_result.sql))
            judge_result = self.judger(
                sql=sql_result,
                natural_language_query=query,
                current_user_message=current_user_message,
            )
            if judge_result.judge:
                return dspy.Prediction(sql=sql_result)
            reasoning = judge_result.reasoning
        return dspy.Prediction(sql=sql_result)


def sanitize_sql(sql):
    sql = extract_sql_regex(sql)
    sql = sql.strip().lower()
    altering_keywords = [
        "insert",
        "update",
        "delete",
        "drop",
        "truncate",
        "alter",
        "create",
        "replace",
        "grant",
        "revoke",
        "comment",
        "rename",
        "set",
        "copy",
        "vacuum",
        "analyze",
    ]

    for keyword in altering_keywords:
        # match full words only to avoid substring match (e.g., 'create' in 'recreate')
        if f" {keyword} " in f" {sql} ":
            return "SELECT 'UNAUTHORIZED';"

    return sql


def extract_sql_regex(text):
    # Case-insensitive extraction from "sql: " followed by anything until ";"
    pattern = r"sql:\s*(.*?);"
    match = re.search(pattern, text, re.IGNORECASE | re.DOTALL)

    if match:
        return match.group(1).strip() + ";"
    else:
        return text
