import dspy
import re
from pydantic import Field
from typing import Annotated
from contextlib import nullcontext
from openinference.instrumentation import safe_json_dumps
from chatdku.setup import DB
from chatdku.core.tools.syllabi_tool.sql_agent import GenerateSQL
from chatdku.config import config
from openinference.semconv.trace import (
    SpanAttributes,
    OpenInferenceSpanKindValues,
    OpenInferenceMimeTypeValues,
)
import time


def _collapse_repeated_lines(text: str, max_consecutive: int = 4) -> str:
    """Collapse long runs of the same consecutive line to avoid runaway repetition.

    Example: if a line repeats 100 times, keep one and add a collapse note.
    """
    if not text:
        return text
    lines = text.splitlines()
    out_lines = []
    prev = None
    count = 0
    for line in lines:
        if line == prev:
            count += 1
        else:
            if prev is not None:
                if count > max_consecutive:
                    out_lines.append(prev)
                    out_lines.append(f"...({count+1} repeated lines collapsed)...")
                else:
                    out_lines.extend([prev] * (count + 1))
            prev = line
            count = 0

    # flush
    if prev is not None:
        if count > max_consecutive:
            out_lines.append(prev)
            out_lines.append(f"...({count+1} repeated lines collapsed)...")
        else:
            out_lines.extend([prev] * (count + 1))

    return "\n".join(out_lines)


def _truncate_long_output(text: str, max_chars: int = 8000) -> str:
    if len(text) <= max_chars:
        return text
    return text[:max_chars] + "\n...[truncated]"


def _dedupe_lines(text: str) -> str:
    """Remove duplicated lines while preserving order."""
    seen = set()
    out = []
    for line in text.splitlines():
        if line not in seen:
            seen.add(line)
            out.append(line)
    return "\n".join(out)


def remove_think_section(text: str) -> str:
    """Removes the first <think>...</think> section (including the tags)."""
    return re.sub(r"<think>.*?</think>", "", text, flags=re.DOTALL)

def fetch_schema(db: DB) -> str:
    """Fetch simple schema description from the 'classes' table."""
    sql = """
        SELECT column_name, data_type
        FROM information_schema.columns
        WHERE table_name = 'classes';
    """
    rows = db.execute(sql)
    schema = {"classes": {col: dtype for col, dtype in rows}}
    return str(schema)


def query_curriculum_db(
    query: Annotated[
        str,
        Field(
            description=(
                "A natural language question to ask a relational database of "
                "class and course data using SQL."
            )
        ),
    ],
) -> str:
    """
    Use SQL to query anything about DKU courses, classes, or instructors
    and return a natural language answer.
    """
    db = DB()  # uses config.psql_uri internally

    sql_agent = GenerateSQL()
    db_schema = fetch_schema(db=db)
    final_sql = sql_agent(query=query, db_schema=db_schema)
    # sanitize/limit SQL generated by the LM to avoid runaway repetition
    final_sql = _collapse_repeated_lines(final_sql)
    final_sql = _dedupe_lines(final_sql)
    final_sql = _truncate_long_output(final_sql, max_chars=12000)

    try:
        rows = db.execute(final_sql)
        tool_out = str(rows)
    except Exception as e:
        tool_out = f"SQL execution error: {e}"

    NLSignature = dspy.Signature(
        "question, tool_output -> result, internal_result"
    )
    predictor = dspy.Predict(NLSignature)

    res = predictor(question=query, tool_output=tool_out)
    # post-process LM output to avoid runaway repetition or extreme length
    start = time.perf_counter()
    res.result = remove_think_section(res.result)
    res.result = _collapse_repeated_lines(res.result)
    res.result = _truncate_long_output(res.result)
    dur = time.perf_counter() - start
    print(f"[QueryCurriculum(simple)] LM post-process time: {dur:.3f}s, len={len(res.result)}")
    return res.result


def QueryCurriculumOuter():
    def QueryCurriculum(query: str, current_user_message: str) -> tuple[object, dict]:
        """
        Takes a natural language query about courses and classes offered at Duke Kunshan University -> generates intermediate SQL query passed into Postgres -> Result formatted in natural language.

        Args: 
            query: String (Detailed question for the classes database in natural lanugage.)
            current_user_message: String (verbatim to user's initial query)
        Returns: 
            String 
        """
        print(f"[QueryCurriculum] ENTER query={query!r}")
        db = DB()

        with (
            config.tracer.start_as_current_span("Query Curriculum DB")
            if hasattr(config, "tracer")
            else nullcontext()
        ) as span:
            if hasattr(config, "tracer"):
                span.set_attributes(
                    {
                        SpanAttributes.OPENINFERENCE_SPAN_KIND: OpenInferenceSpanKindValues.RETRIEVER.value,
                        SpanAttributes.INPUT_VALUE: safe_json_dumps(
                            dict(query=query)
                        ),
                        SpanAttributes.INPUT_MIME_TYPE: OpenInferenceMimeTypeValues.JSON.value,
                    }
                )

            sql_agent = GenerateSQL()
            db_schema = fetch_schema(db=db)
            final_sql = sql_agent(query=query, current_user_message=current_user_message, db_schema=db_schema)
            # sanitize generated SQL to avoid runaway repetition or duplication
            final_sql = _collapse_repeated_lines(final_sql)
            final_sql = _dedupe_lines(final_sql)
            final_sql = _truncate_long_output(final_sql, max_chars=12000)
            print(f"[QueryCurriculum] generated SQL (len={len(final_sql)}): {final_sql}")

            try:
                rows = db.execute(final_sql)
                tool_out = str(rows)
                print(f"[QueryCurriculum] DB returned rows: {rows}")
            except Exception as e:
                rows = None
                tool_out = f"SQL execution error: {e}"
                print(f"[QueryCurriculum] DB execution error: {e}")

            NLSignature = dspy.Signature("question, tool_output -> result")

            start = time.perf_counter()
            res = dspy.Predict(NLSignature)(question=query, tool_output=tool_out)

            res.result = remove_think_section(res.result)
            # collapse repeated lines and truncate excessively long outputs
            res.result = _collapse_repeated_lines(res.result)
            res.result = _truncate_long_output(res.result)
            dur = time.perf_counter() - start
            print(f"[QueryCurriculum] LM call time: {dur:.3f}s, result_len={len(res.result)}")

            result = res.result
            internal_result = {"sql": final_sql}
            print(f"[QueryCurriculum] LM result preview: {str(result)[:200]!r}")
            print(f"[QueryCurriculum] internal_result: {internal_result}")

            if hasattr(config, "tracer"):
                span.set_attributes(
                    {
                        SpanAttributes.OUTPUT_VALUE: safe_json_dumps(dict(result=result)),
                        SpanAttributes.OUTPUT_MIME_TYPE: OpenInferenceMimeTypeValues.JSON.value,
                    }
                )

        return result, internal_result

    return QueryCurriculum

query_curriculum_tool = dspy.Tool(query_curriculum_db)