import dspy
from openinference.instrumentation import safe_json_dumps
from openinference.semconv.trace import (
    OpenInferenceMimeTypeValues,
    OpenInferenceSpanKindValues,
    SpanAttributes,
)
from opentelemetry.trace import Status, StatusCode

from chatdku.core.tools.retriever.base_retriever import NodeWithScore, nodes_to_OTLP
from chatdku.core.tools.syllabi_tool.generate_sql import GenerateSQL
from chatdku.core.utils import span_ctx_start
from chatdku.setup import DB


class JudgeSQLSignature(dspy.Signature):
    """
    Judge the SQL query generated by another LLM agent.
    You are to check the validity of the SQL query, and whether the query follows
    the natural_language_query.
    Check whether the results of the query are able to answer the natural_language_query.
    """

    sql = dspy.InputField()
    natural_language_query = dspy.InputField(
        desc="The information the planner agent wants to retrieve by using this tool."
    )
    current_user_message = dspy.InputField(desc="User's initial prompt")
    results = dspy.InputField(desc="The results of the query")
    judge: bool = dspy.OutputField(
        desc="Whether the SQL query is valid. Answer in `True` or `False`."
    )


def QueryCurriculumOuter(N=3):
    def QueryCurriculum(query: str, current_user_message: str) -> tuple[str, dict]:
        """
        Takes a natural language query about courses and classes offered at Duke Kunshan University -> generates intermediate SQL query passed into Postgres -> Result formatted in natural language.

        Args:
            query: String (The information you want to retrieve by using this tool.)
            current_user_message: String (verbatim to user's initial query)
        Returns:
            String
        """
        db = DB()
        judger = dspy.ChainOfThought(JudgeSQLSignature)
        sql_agent = GenerateSQL()
        db_schema = fetch_schema(db=db)
        internal_result = {}
        tool_out = ""
        reasoning = ""

        for _ in range(N):
            sql = sql_agent(
                query=query,
                current_user_message=current_user_message,
                db_schema=db_schema,
                reasoning=reasoning,
            ).sql
            internal_result = {"sql": sql}
            nodes = []

            with span_ctx_start(
                "Query Curriculum DB", OpenInferenceSpanKindValues.RETRIEVER
            ) as span:
                span.set_attributes(
                    {
                        SpanAttributes.INPUT_VALUE: safe_json_dumps(
                            dict(query=query, sql=sql)
                        ),
                        SpanAttributes.INPUT_MIME_TYPE: OpenInferenceMimeTypeValues.JSON.value,
                    }
                )

                try:
                    rows = db.execute(sql)
                    tool_out = str(rows)
                    for i, row in enumerate(rows):
                        nodes.append(
                            NodeWithScore(
                                node_id=str(i),
                                text=str(row),
                                metadata={},
                                score=1.0,
                            )
                        )
                    span.set_attributes(nodes_to_OTLP(nodes))
                except Exception as e:
                    rows = None
                    tool_out = f"SQL execution error: {e}"
                    span.set_status(Status(StatusCode.ERROR), str(e))

            judgement = judger(
                sql=sql,
                natural_language_query=query,
                current_user_message=current_user_message,
                results=tool_out,
            )
            if judgement.judge:
                break
            reasoning = judgement.reasoning

        return tool_out, internal_result

    return QueryCurriculum


def fetch_schema(db: DB) -> str:
    """Fetch simple schema description from the 'classes' table."""
    sql = """
        SELECT column_name, data_type
        FROM information_schema.columns
        WHERE table_name = 'classes';
    """
    rows = db.execute(sql)
    schema = {"classes": {col: dtype for col, dtype in rows}}
    return str(schema)
